//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.TreeObservation = new HashSet<TreeObservation>();
        }
    
        public int InventoryID { get; set; }
        public int EstateID { get; set; }
        public System.DateTime Date { get; set; }
        public int PerformerID { get; set; }
    
        public virtual Estate Estate { get; set; }
        public virtual Performer Performer { get; set; }
        public virtual ICollection<TreeObservation> TreeObservation { get; set; }
    }
}
